### ISSUE TITLE
Иногда после успешной отправки чека в ответ приходит null вместо объекта Reciept

### ISSUE THREAD

**Issue by mykola-petiukh** [igorbunov/checkbox-in-ua-php-sdk#14]
Был как минимум один случай, что после отправки `SellReceipt` в ответ вместо `Receipt` прилетает `null`.
Этот случай залогирован и, так уж случилось, момент отправки того чека есть на видео. Смогу предоставить в личной переписке, если надо.

**Comment by igorbunov** [comment]
> Был как минимум один случай, что после отправки `SellReceipt` в ответ вместо `Receipt` прилетает `null`. Этот случай залогирован и, так уж случилось, момент отправки того чека есть на видео. Смогу предоставить в личной переписке, если надо.

в try catch запрос завернули? может ошибки были какие-то. вообще если ответ от апишки прям null приходит, то скорее всего на стороне чекбокса какие-то проблемы, надо с ними общатся. Мы с такой ошибкой пока не сталкивались

**Comment by mykola-petiukh** [comment]
> в try catch запрос завернули?

Да. 

> может ошибки были какие-то

Вообще никаких. Просто null вернулся. Чек в кабинете Чекбокса отобразился.

> Мы с такой ошибкой пока не сталкивались

Я тоже всего один раз.
