### ISSUE TITLE
Как возвращать чеки

### ISSUE THREAD

**Issue by Vladislavlr** [igorbunov/checkbox-in-ua-php-sdk#15]
Как возвращать чеки суть в том что нету поля в которе вписать id чека к которому нужно вернуть все товары.
Вот таких параметров нет
  "related_receipt_id":  - даний параметр як опція для зв'язку між чеком продажу і повернення. При поверненні можна передати ід чеку продажу.
  "previous_receipt_id":  - id попереднього чеку, якщо його передати, то виконується перевірка чи є вказаний чек попереднім
 "technical_return":  -  флаг про технічне повернення чеку.

**Comment by Vladislavlr** [comment]
@igorbunov а как мне сделать возврат чека (я вижу в товаре есть опция для возврата товара) но как передать id чека к которому применится возврат?

**Comment by igorbunov** [comment]
в документации нигде не указывается айди предыдущего чека. для налоговой скорее всего важна сумма возврата
https://dev-api.checkbox.in.ua/api/redoc#operation/create_receipt_api_v1_receipts_sell_post
