### ISSUE TITLE
При формуванні чеку ціна за товар не коректна

### ISSUE THREAD

**Issue by fobus821** [igorbunov/checkbox-in-ua-php-sdk#25]
version 1.2.10 php: 7.3 x64
Помічено тільки з ціною коли копійки = 20. Наприклад 2230.20 або 45.20 або 1980.20 і так далі.
Суть в тому що значення чомусь змінюється з 4520 на 4519
і при розрахунку карткою видає помилку: Для розрахунку карткою використання решти 0.01 не можливе.
Наприклад конкрений випадок:
echo $FinalPrice         = $product['final_price']; // 2230.20
echo $FinalPrice         = floatval($product['final_price']); // 2230.2
echo $FinalPrice         = $FinalPrice * 100; //223020

після формування чеку результат: 

 ["goods"]=>
  object(igorbunov\Checkbox\Models\Receipts\Goods\Goods)#38 (1) {
    ["results"]=>
    array(1) {
      [0]=>
      object(igorbunov\Checkbox\Models\Receipts\Goods\GoodItemModel)#47 (7) {
        ["good"]=>
        object(igorbunov\Checkbox\Models\Receipts\Goods\GoodModel)#36 (8) {
          ["code"]=>
          string(5) "12998"
          ["barcode"]=>
          string(0) ""
          ["name"]=>
          string(39) "PETLAS   IMPERIUM PT515 91V   195/65R15"
          ["header"]=>
          string(0) ""
          ["footer"]=>
          string(0) ""
          ["uktzed"]=>
          string(0) ""
          **["price"]=>
          int(223019)**
          ["taxes"]=>
          object(igorbunov\Checkbox\Models\Receipts\Taxes\GoodTaxes)#44 (1) {
            ["results"]=>
            array(1) {
              [0]=>
              object(igorbunov\Checkbox\Models\Receipts\Taxes\GoodTax)#42 (11) {
                ["id"]=>
                string(36) "358d5577-0b7f-4501-b3f4-ccbe9380c33d"
                ["code"]=>
                string(1) "1"
                ["label"]=>
                string(13) "Без ПДВ"
                ["symbol"]=>
                string(2) "Е"
                ["rate"]=>
                string(1) "0"
                ["extra_rate"]=>
                NULL
                ["included"]=>
                string(1) "1"
                ["created_at"]=>
                string(25) "2022-02-01T00:53:18+00:00"
                ["updated_at"]=>
                string(25) "2022-02-01T00:54:06+00:00"
                ["value"]=>
                int(0)
                ["extra_value"]=>
                string(0) ""
              }
            }
          }
        }
        ["good_id"]=>
        string(0) ""
        ["sum"]=>
        int(0)
        ["quantity"]=>
        int(1000)
        ["is_return"]=>
        bool(false)
        ["taxes"]=>
        object(igorbunov\Checkbox\Models\Receipts\Taxes\GoodTaxes)#44 (1) {
          ["results"]=>
          array(1) {
            [0]=>
            object(igorbunov\Checkbox\Models\Receipts\Taxes\GoodTax)#42 (11) {
              ["id"]=>
              string(36) "358d5577-0b7f-4501-b3f4-ccbe9380c33d"
              ["code"]=>
              string(1) "1"
              ["label"]=>
              string(13) "Без ПДВ"
              ["symbol"]=>
              string(2) "Е"
              ["rate"]=>
              string(1) "0"
              ["extra_rate"]=>
              NULL
              ["included"]=>
              string(1) "1"
              ["created_at"]=>
              string(25) "2022-02-01T00:53:18+00:00"
              ["updated_at"]=>
              string(25) "2022-02-01T00:54:06+00:00"
              ["value"]=>
              int(0)
              ["extra_value"]=>
              string(0) ""
            }
          }
        }
        ["discounts"]=>
        NULL
      }
    }
  }

**Comment by igorbunov** [comment]
> version 1.2.10 php: 7.3 x64 Помічено тільки з ціною коли копійки = 20. Наприклад 2230.20 або 45.20 або 1980.20 і так далі. Суть в тому що значення чомусь змінюється з 4520 на 4519 і при розрахунку карткою видає помилку: Для розрахунку карткою використання решти 0.01 не можливе. Наприклад конкрений випадок: echo $FinalPrice = $product['final_price']; // 2230.20 echo $FinalPrice = floatval($product['final_price']); // 2230.2 echo $FinalPrice = $FinalPrice * 100; //223020
> 
> після формування чеку результат:
> 
> ["goods"]=> object(igorbunov\Checkbox\Models\Receipts\Goods\Goods)#38 (1) { ["results"]=> array(1) { [0]=> object(igorbunov\Checkbox\Models\Receipts\Goods\GoodItemModel)#47 (7) { ["good"]=> object(igorbunov\Checkbox\Models\Receipts\Goods\GoodModel)#36 (8) { ["code"]=> string(5) "12998" ["barcode"]=> string(0) "" ["name"]=> string(39) "PETLAS IMPERIUM PT515 91V 195/65R15" ["header"]=> string(0) "" ["footer"]=> string(0) "" ["uktzed"]=> string(0) "" **["price"]=> int(223019)** ["taxes"]=> object(igorbunov\Checkbox\Models\Receipts\Taxes\GoodTaxes)#44 (1) { ["results"]=> array(1) { [0]=> object(igorbunov\Checkbox\Models\Receipts\Taxes\GoodTax)#42 (11) { ["id"]=> string(36) "358d5577-0b7f-4501-b3f4-ccbe9380c33d" ["code"]=> string(1) "1" ["label"]=> string(13) "Без ПДВ" ["symbol"]=> string(2) "Е" ["rate"]=> string(1) "0" ["extra_rate"]=> NULL ["included"]=> string(1) "1" ["created_at"]=> string(25) "2022-02-01T00:53:18+00:00" ["updated_at"]=> string(25) "2022-02-01T00:54:06+00:00" ["value"]=> int(0) ["extra_value"]=> string(0) "" } } } } ["good_id"]=> string(0) "" ["sum"]=> int(0) ["quantity"]=> int(1000) ["is_return"]=> bool(false) ["taxes"]=> object(igorbunov\Checkbox\Models\Receipts\Taxes\GoodTaxes)#44 (1) { ["results"]=> array(1) { [0]=> object(igorbunov\Checkbox\Models\Receipts\Taxes\GoodTax)#42 (11) { ["id"]=> string(36) "358d5577-0b7f-4501-b3f4-ccbe9380c33d" ["code"]=> string(1) "1" ["label"]=> string(13) "Без ПДВ" ["symbol"]=> string(2) "Е" ["rate"]=> string(1) "0" ["extra_rate"]=> NULL ["included"]=> string(1) "1" ["created_at"]=> string(25) "2022-02-01T00:53:18+00:00" ["updated_at"]=> string(25) "2022-02-01T00:54:06+00:00" ["value"]=> int(0) ["extra_value"]=> string(0) "" } } } ["discounts"]=> NULL } } }

поправил, версия 1.2.13
