### ISSUE TITLE
Не правильно повертає тип помилки для  "Касир вже працює з даною касою" 

### ISSUE THREAD

**Issue by ridiks10** [igorbunov/checkbox-in-ua-php-sdk#27]
Не правильно повертає тип помилки для  "Касир вже працює з даною касою"  повертає NoActiveShift, а мало б повернути 
AlreadyOpenedShift.
Рішення:

файл: CheckboxJsonApi.php
```
private function validateResponseStatus($json, int $statusCode): void
    {
        switch ($statusCode) {
            case 400:
                if (!empty($json['message']) and $json['message'] == 'Касир вже працює з даною касою') {
                    throw new AlreadyOpenedShift($json['message']);
                }

                if (!empty($json['message']) and $json['message'] == 'Зміну не відкрито') {
                    throw new NoActiveShift($json['message']);
                }
```

**Comment by igorbunov** [comment]
поправил. также посмотрел по доке, у них там сейчас много ошибок навешано на 400 статус код. некоторые попарсил по тексту сообщения. остальные по умолчанию будут возвращать exception BadRequest
https://github.com/igorbunov/checkbox-in-ua-php-sdk/pull/28/files
